# Generated by Django 4.2.3 on 2023-11-03 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAluno', '0008_alter_telefone_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('serie_recomendacao', models.CharField(max_length=1)),
                ('assunto', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appBiblio.autor')),
            ],
        ),
        migrations.CreateModel(
            name='FichaEmprestimo',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('retirada', models.DateField()),
                ('devolucao', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appAluno.aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appBiblio.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('numero', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('prateleira', models.IntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appBiblio.livro')),
            ],
        ),
    ]
