# Generated by Django 4.2.3 on 2023-11-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBiblio', '0002_remove_autor_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='serie_recomendacao',
        ),
    ]
