# Generated by Django 4.2.3 on 2023-11-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBiblio', '0003_remove_livro_assunto_remove_livro_serie_recomendacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='exemplares',
            field=models.IntegerField(default=0),
        ),
    ]
